version: "3.4"

services:
  camunda-api:
    profiles:
      - "runcontainers"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - "8080:8080"
    labels:
      org.springframework.boot.ignore: true
    environment:
      SPRING_DATASOURCE_URL:
      CAMUNDA_BPM_AUTHORIZATION_ENABLED: true
      LDAP_AUTH_ENABLED: true
      LDAP_CAMUNDA_WEBAPPS_ADMIN_GROUP_NAME: admins
      LDAP_CAMUNDA_ADMIN_USER: camunda
      LDAP_SERVER_URI: "ldap://openldap:1389"
      LDAP_ACCEPTUNTRUSTEDCERTIFICATES: false
      LDAP_MANAGER_DN: uid=camunda,cn=users,dc=example,dc=org
      LDAP_MANAGER_PASSWORD: camunda
      LDAP_SEARCH_BASE_DN: dc=example,dc=org
      LDAP_USER_SEARCH_BASE:
      LDAP_USER_SEARCH_FILTER: (objectclass=person)
      LDAP_USER_ID_ATTRIBUTE: uid
      LDAP_USER_FIRSTNAME_ATTRIBUTE: givenName
      LDAP_USER_LASTNAME_ATTRIBUTE: sn
      LDAP_USER_EMAIL_ATTRIBUTE: mail
      LDAP_USER_PASSWORD_ATTRIBUTE: userPassword
      LDAP_GROUP_SEARCH_BASE:
      LDAP_GROUP_SEARCH_FILTER: (objectclass=groupOfNames)
      LDAP_SORTCONTROLSUPPORTED: false
      LDAP_AUTHORIZATIONCHECKENABLED: true
      LDAP_GROUP_SEARCH_GROUPMEMBER_ATTRIBUTE: member
    depends_on:
      - openldap
  openldap:
    build:
      context: /ldap
      dockerfile: Dockerfile
    restart: always
    ports:
      - 1389:1389
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword